"""add status and expiration date to analyses

Revision ID: 1811208f4743
Revises: a9d5459e02cf
Create Date: 2026-09-25 13:54:55.467964

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1811208f4743"
down_revision = "a9d5459e02cf"
branch_labels = None
depends_on = None


def upgrade():
    status_enum = postgresql.ENUM(
        "pending",
        "finished",
        "processing",
        "error",
        name="status",
    )

    status_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_analyses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                sa.Enum("pending", "finished", "processing", "error", name="status"),
                server_default="pending",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_analyses", schema=None) as batch_op:
        batch_op.drop_column("expires_at")
        batch_op.drop_column("status")

    # ### end Alembic commands ###
